### ISSUE TITLE
[GO] [DX list problems] Add adjective "metastatic" to list of initial diagnoses

### ISSUE THREAD

**Issue by jliphard** [jliphard/CancerBase#19]
Some people are immediately diagnosed with metastatic cancer - and they feel left out. How do we cover this possibility.

**Comment by jliphard** [comment]
Could we use http://jquery-plugins.net/autojs-auto-complete-plugin-from-dictionary

**Comment by jliphard** [comment]
Problem solved with Select2 - see ref implementation and new data structures

**Comment by ebcopur** [comment]
Will do this with a multiple select - autocomplete component. However, two things:
- If we allow users to choose more than one initial DX, which will we publish to pubnub?
- What is the DXdictionary var in https://github.com/jliphard/CancerBase/blob/master/initialDXchoices.js actually used for?
- I mostly use existing Angular2 components from http://www.primefaces.org/primeng/ when available instead of writing wrappers for jquery plugins manually, and it is easier if we generate the data in the structures these require.

**Comment by jliphard** [comment]
> On Jul 4, 2016, at 6:08 PM, ebcopur <notifications@github.com> wrote:
> 
> Will do this with a multiple select - autocomplete component. However, two things:
> 
> If we allow users to choose more than one initial DX, which will we publish to pub nub?
Good question - can we publish a string such as Bone:Breast:Lung?
> What is the DXdictionary var in https://github.com/jliphard/CancerBase/blob/master/initialDXchoices.js <https://github.com/jliphard/CancerBase/blob/master/initialDXchoices.js> actually used for?
Nothing - I’ll delete it.
> I mostly use existing Angular2 components from http://www.primefaces.org/primeng/ <http://www.primefaces.org/primeng/> when available instead of writing wrappers for jquery plugins manually, and it is easier if we generate the data in the structures these require.
OK - shall I change it for you?

**Comment by ebcopur** [comment]
> Good question - can we publish a string such as Bone:Breast:Lung?

Sure. 

> OK - shall I change it for you?

No I can change it, just meant for future reference.
